### ISSUE TITLE
Alpine error

### ISSUE THREAD

**Issue by Bilyachenko** [Hujjat/shopify-sunrise#2]
Hi
cooll theme, but get alpine errors - https://prnt.sc/8jnEXYmaFxoR
how fast fix?

**Comment by Hujjat** [comment]
Hey @Bilyachenko 

I noticed this error today in most of my projects. I couldn't find a solution for this yet. 

Here is a temporary solution. 

This error happens when you run `npx mix watch` which compiles the JavaScript files. 

Everything works if you run the production command. `npx mix --production`. 

If you're not making changes to your JavaScript, comment the javaScript compilation in `webpack.mix.js` when running `npx mix watch`

It seems like the error is because of ES17 async await functions. 

Very strange but that's my solution for now. I will post the solution if I find it.

**Comment by Bilyachenko** [comment]
today it seems to have worked fine, strange, maybe some update created an error?

**Comment by Hujjat** [comment]
Closing this. As it's working fine now. 

I anyone have issue in future, try to do production build for JavaScript.
